mrjones2014/legendary.nvim

README.md, lua/legendary/bindings.lua, lua/legendary/config.lua
Fixes: #52 
Also sets up a default function defined as such:
```lua
function(kind)
if kind == 'legendary.items' then
return 'Legendary'
end
-- Convert kind to Title Case (e.g. legendary.keymaps => Legendary Keymaps)
return string.gsub(' ' .. kind:gsub('%.', ' '), '%W%l', string.upper):sub(2)
end
=> Allow select_prompt config to be a string or a function

README.md, lua/legendary/bindings.lua, lua/legendary/config.lua, lua/legendary/formatter.lua, lua/legendary/scratchpad.lua, tests/legendary/formatter_spec.lua
Fixes #55 
Adds a config option to pass a function which takes the item as a parameter and must return a table of column values.
=> Add support for custom formatting values

lua/legendary/utils.lua, teal/legendary/utils.tl
Resolves: #120 
1. Create a command through legendary
2. Try to run it through the legendary finder
=> set default opts to empty table

lua/legendary/compat/which-key.lua, teal/legendary/compat/which-key.tl
Resolves: #127 
1. Set up a keymap via which-key.nvim for a mode other than normal 
2. Check that legendary sees the mode correctly by searching for it in `:Legendary keymaps`
=> check for mode in which-key opts

.github/workflows/lint.yml, Makefile, README.md, lua/legendary/bindings.lua, lua/legendary/executor.lua, lua/legendary/types.lua, lua/legendary/utils.lua, teal/legendary/bindings.tl, teal/legendary/executor.tl, teal/legendary/types.tl, teal/legendary/utils.tl, tests/legendary/utils_spec.lua
Allows separate descriptions per-mode. Also adds the ability to specify the description under `item.opts.desc` instead of `item.description` if you prefer (since this is what the Neovim APIs reference internally).
Resolves: #108 
1. Add a keymap which has per-mode mappings, and in each mode, specify either `description` or `opts.desc`
2. Make sure the keymaps work in each mode
3. Make sure the rest of your existing keymaps, commands, and autocmds work
=> Allow separate descriptions per-mode

README.md, lua/legendary/bindings.lua, lua/legendary/compat/which-key.lua, lua/legendary/config.lua, lua/legendary/init.lua, lua/legendary/types.lua, lua/legendary/utils.lua, teal/legendary/bindings.tl, teal/legendary/compat/which-key.tl, teal/legendary/config.tl, teal/legendary/init.tl, teal/legendary/types.tl, teal/legendary/utils.tl
Resolves: #[issue number] 
1. Please leave detailed testing instructions
=> let which-key handle key binding if which-key integration is used

README.md, lua/legendary/bindings.lua, lua/legendary/filters.lua, lua/legendary/types.lua, teal/legendary/bindings.tl, teal/legendary/filters.tl, teal/legendary/types.tl, teal/vim.d.tl
Resolves: #129 
1. Call `require('legendary').find(nil, require('legendary.filters').mode('n'))`, it should only show normal mode mappings
2. Call `require('legendary').find(nil, require('legendary.filters').mode('i'))`, it should only show insert mode mappings
=> Implement item filters

lua/legendary/compat/which-key.lua, teal/legendary/compat/which-key.tl
Resolves: #78  
1. Make sure `which-key` is loaded _after_ legendary
2. Setup which-key integration with `auto_load_which_key = true`
3. Make sure keymaps registered via which-key are picked up via legendary
=> Use package.searchers to make which-key integration not dependent on load order

lua/legendary/bindings.lua, teal/legendary/bindings.tl
Removed this to prevent a `<function>1` from being displayed in `nvim`
=> Remove print statement that was left in `bindings.tl`

README.md, doc/legendary-api.txt, lua/legendary/bindings.lua, lua/legendary/cmds.lua, lua/legendary/config.lua, lua/legendary/formatter.lua, lua/legendary/init.lua, lua/legendary/types.lua, lua/legendary/utils.lua, teal/legendary/bindings.tl, teal/legendary/cmds.tl, teal/legendary/config.tl, teal/legendary/executor.tl, teal/legendary/formatter.tl, teal/legendary/init.tl, teal/legendary/types.tl, teal/legendary/utils.tl
Resolves: #149 
Create/bind a function such as 
```lua
require("legendary.bindings").bind_functions({
{
function(args)
if args then vim.pretty_print(args) end
vim.lsp.buf.code_action({
filter = function(a)
return a.isPreferred
end,
apply = true,
})
end,
description = "Auto Fix...",
opts = { buffer = bufnr },
},
}, "LSP")
```
Check that it's displayed in the menu and correctly called. Further, if `opts.buffer` is set, then it should be available only for the specified buffer. If you're in visual mode, the function above should also print the selection range.
----------
I'll write proper commit messages later.
=> feat: allow arbitrary Lua functions without mapping to a command 

Makefile, README.md, lua/legendary/bindings.lua, lua/legendary/formatter.lua, teal/legendary/bindings.tl, teal/legendary/formatter.tl, tests/legendary/formatter_spec.lua
Resolves: #161 
Also: Resolves: #153 
With the following config, columns should be aligned:
```lua
local legendary = require('legendary')
local filters = require('legendary.filters')
legendary.bind_commands({
{ ':Mason',  description = '查看lsp/dap包管理器窗口' },
{ ':MasonInstall',  unfinished = true, description = '安装或重新安装lsp/dap包'},
{ ':MasonUninstall',  unfinished = true, description = '卸载lsp/dap包'},
{ ':MasonUninstallAll',  description = '卸载所有lsp/dap包'},
{ ':MasonLog',  description = '在一个新tab页中打开mason.nvim的日志文件'},
})
legendary.bind_commands({
{ ':LspInstall',  unfinished = true, description = '安装或重新安装lsp包(lspconfig名称格式)' },
{ ':LspUninstall',  unfinished = true, description ='卸载lsp包(lspconfig名称格式)' },
})
legendary.find({
--TODO find命令里应该也可以修改select_prompt
filters = {
--只显示当前模式的映射 …
```
=> dynamically compute padding on the fly

README.md, lua/legendary/bindings.lua, lua/legendary/filters.lua, lua/legendary/types.lua, teal/legendary/bindings.tl, teal/legendary/filters.tl, teal/legendary/types.tl
Resolves: #160  
1. Pass `select_prompt` option to find function.
=> allow passing `select_prompt` for one-shot finds

README.md, lua/legendary/config.lua, lua/legendary/scratchpad.lua, lua/legendary/types.lua, plugin/legendary.lua, teal/legendary/config.tl, teal/legendary/scratchpad.tl, teal/legendary/types.tl
Resolves: #169 
1. Put stuff in scratchpad
2. Close scratchpad 
3. Reopen scratchpad 
4. It should have the original contents
5. Quit Neovim
6. Reopen Neovim and scratchpad
7. It should have the original contents
=> save scratchpad contents to a cache file

lua/legendary/compat/which-key.lua, teal/legendary/compat/which-key.tl
Resolves: #181 
1. Which-key.nvim keymaps should be added to legendary.nvim when using the integration
=> fix which-key parsing

README.md, lua/legendary/config.lua, lua/legendary/data/autocmd.lua, lua/legendary/data/command.lua, lua/legendary/data/keymap.lua, tests/legendary/data/autocmd_spec.lua, tests/legendary/data/command_spec.lua, tests/legendary/data/keymap_spec.lua
Resolves: #201 
1. Run tests
1. Set default opts and make sure they apply by default
=> allow default options to be passed to keymaps, commands, and autocmds

doc/table_structures/COMMANDS.md, lua/legendary/api/executor.lua, lua/legendary/data/command.lua, lua/legendary/data/keymap.lua, lua/legendary/util.lua, tests/legendary/data/command_spec.lua
Resolves: #215 
An example command for `Comment.nvim` comment toggling:
```lua
require('legendary').command({
':Comment',
{
n = 'gcc',
v = 'gc',
},
description = 'Toggle comment',
})
```
=> Allow per-mode implementations for commands

lua/legendary/data/command.lua, lua/legendary/filters.lua
Resolves: #220 
1. See reproduction steps in issue.
=> Fix mode filters

doc/table_structures/AUTOCMDS.md, doc/table_structures/COMMANDS.md, doc/table_structures/KEYMAPS.md, lua/legendary/data/autocmd.lua, lua/legendary/data/command.lua
=> feat: allow autocmds and commands to be hidden

README.md, lua/legendary/api/cmds.lua, lua/legendary/api/db/client.lua, lua/legendary/api/db/wrapper.lua, lua/legendary/config.lua, lua/legendary/data/itemgroup.lua, lua/legendary/data/itemlist.lua, lua/legendary/data/keymap.lua, lua/legendary/log.lua, lua/legendary/ui/init.lua
Resolves: #235 
Update your config to include this new dependency (only required for frecency sorting): https://github.com/kkharji/sqlite.lua
e.g.
```lua
use { 'mrjones2014/legendary.nvim', requires = 'kkharji/sqlite.lua' }
```
1. Ensure that everything like item picking and execution still works
2. Test that items seem to be sorted by both frequency and recency of use
3. Test that items _within item groups_ are also sorted the same way
=> feat(sort): Sort by "frecency" if sqlite is available

README.md, lua/legendary/api/db/wrapper.lua, lua/legendary/data/autocmd.lua, lua/legendary/data/command.lua, lua/legendary/data/function.lua, lua/legendary/data/itemgroup.lua, lua/legendary/data/itemlist.lua, lua/legendary/data/keymap.lua
Resolves: #251 
The only time frecency score should reset is if fields in the table below are changed:
| Item type | Fields                            |
| --------- | --------------------------------- |
| Autocmd   | `description`                     |
| Command   | name (`tbl[1]`), `description`    |
| Function  | `description`                     |
| Keymap    | `description`                     |
| Group     | `name` (`itemgroup='Group name'`) |
=> feat(frecency): use separate IDs for frecency scoring

lua/legendary/data/keymap.lua, tests/legendary/data/keymap_spec.lua
Resolves: #271
1. `require('legendary').keymap({'<leader><leader>', description = 'find me pls', mode = { 'v' }})`
2. trigger legendary from visual mode
3. search for 'find me pls'
4. item should appear
=> fix(keymaps): track mode(s) correctly for description-only keymaps

lua/legendary/init.lua
Resolves: #270 
1. Follow reproduction steps in linked issue, it should no longer be reproducible
=> fix(setup): remove duplicate `:apply()` calls

lua/legendary/api/cmds.lua, lua/legendary/api/executor.lua
Resolves: #277 
1. Execute `:LegendaryEvalLines` from visual mode on some Lua code via the finder UI
2. It should work correctly
3. Visual commands that do NOT accept marks should also still work
=> fix(executor): Commands that accept a range will be executed with marks (`'<,'>`) added if triggered from visual mode

doc/MAPPING_DEVELOPMENT.md, lua/legendary/api/cmds.lua, lua/legendary/config.lua, lua/legendary/ui/scratchpad.lua
Resolves: #279 
For each of `current`, `float`, `split`, and `vsplit`, run the following test where the chosen value is referred to as `[method]`:
1. `:LegendaryScratch [method]` should open the scratchpad according to specified `[method]`, overriding the value of `config.scratchpad.view`
2. `:LegendaryScratchToggle [method]` should toggle the scratchpad according to specified `[method]`, overriding the value of `config.scratchpad.view`
=> new(scratchpad): `:LegendaryScratch` and `:LegendaryScratchToggle` now accept an argument to override `Config.scratchpad.view`

lua/legendary/config.lua, lua/legendary/ui/format.lua
Thanks for the plugin 💙 
The case where you don't have the necessary font to display the default icons but also have no need to replace the whole `default_formatter_function`
=> feat: support overriding icons for default items formatter

lua/legendary/integrations/which-key.lua
Resolves: #310 
1. Register an item with which-key like so:
```lua
require('which-key').register({
f = {
name = 'WhichKey: Files', -- optional group name
desc = 'Some which key items',
q = { '<cmd>Telescope find_files<cr>', 'Find File' },
},
}, {
prefix = '<leader>',
})
```
It should be registered in legendary under an item group with name `WhichKey: Files` and description `Some which key items`.
=> feat: Support for `which-key.nvim` groups into `legendary.nvim` `ItemGroups`

README.md, doc/table_structures/AUTOCMDS.md, doc/table_structures/COMMANDS.md, doc/table_structures/FUNCTIONS.md, doc/table_structures/KEYMAPS.md, lua/legendary/api/executor.lua, lua/legendary/data/itemlist.lua, lua/legendary/data/keymap.lua, lua/legendary/filters.lua, lua/legendary/ui/init.lua, lua/legendary/util.lua, tests/legendary/data/itemlist_spec.lua
Resolves: #256 
1. Create a keymap with custom filters like `{ '<C-v>', description = 'filtree open in split', filters = { filetype = 'filetree' } }`
1. Create a new buffer and `:set filetype=filetree`
1. The keymap you created in step 1 should only appear in the UI when triggered from the `filetree` buffer
1. Repeat steps 1-3 but for a `buftype` instead of a filetype
1. Also test with a custom function filter as described in the changes to `KEYMAPS.md`
=> feat(keymaps): Add syntax to filter keymaps from UI dynamically

.github/workflows/check-pr-title.yml, lua/legendary/init.lua
Resolves: #323 
1. Which-key mappings like this should be picked up
```lua
require('legendary').setup({
which_key = {
mappings = {
['<space>f'] = {
function()
print('foo')
end,
'Print foo',
},
},
},
})
```
=> fix: `Config.which_key.mappings` are now registered properly

README.md, doc/EXTENSIONS.md, lua/legendary/config.lua, lua/legendary/data/itemlist.lua, lua/legendary/data/keymap.lua, lua/legendary/extensions/init.lua, lua/legendary/extensions/nvim_tree.lua, lua/legendary/init.lua
Resolves: #183 
1. Load the plugin from this branch, and setup with `require('legendary').setup({ extensions = { nvim_tree = true } })`
2. Make sure nvim-tree is installed
3. Open nvim-tree
4. Trigger the legendary.nvim finder from the nvim-tree window
5. It should show the nvim-tree keymaps
6. Triggering the legendary.nvim finder from _any other window_ should _not_ show the nvim-tree keymaps
=> feat(api): Implement extension API and nvim_tree extension

README.md, doc/EXTENSIONS.md, lua/legendary/config.lua, lua/legendary/extensions/smart_splits.lua, lua/legendary/ui/init.lua
1. Install `smart-splits.nvim` and enable extension
2. Commands should be loaded into legendary
=> feat(extension): add smart-splits.nvim extension

README.md, doc/EXTENSIONS.md, lua/legendary/extensions/op_nvim.lua
1. Install `op.nvim`
2. Commands should be loaded into legendary when you trigger the UI
=> feat: add op.nvim extension

lua/legendary/config.lua, lua/legendary/ui/format.lua
Resolves: #331 
1. Create the item described in the issue
2. Launch the UI
=> fix(ui): Normalize type of `opts.pattern` for autocmds in UI

README.md, lua/legendary/extensions/diffview.lua, lua/legendary/extensions/op_nvim.lua, lua/legendary/extensions/smart_splits.lua
Resolves: #338 
```lua
require('legendary').setup({
extensions = {
diffview = true,
},
})
```
Run `:DiffviewOpen`. Commands from `diffview.nvim` should now all appear in `legendary.nvim`, and keymaps from `diffview.nvim` should appear, filtered by the correct view type, e.g. `diff2` keymaps should only show up on the `diff2` view.
=> feat(extension): implement extension for diffview.nvim

README.md, doc/table_structures/KEYMAPS.md, doc/table_structures/README.md, lua/legendary/data/autocmd.lua, lua/legendary/data/command.lua, lua/legendary/data/filters.lua, lua/legendary/data/function.lua, lua/legendary/data/itemgroup.lua, lua/legendary/data/itemlist.lua, lua/legendary/data/keymap.lua
Resolves: #346 
1. Create an item of each type with the `filters` property set
2. Ensure the filters work as expected
=> feat(api): filters can now be applied to all item types instead of just keymaps

lua/legendary/ui/scratchpad.lua
Resolves: #358 
1. Open scratchpad buffer with lspconfig and lua_ls configured
2. lua_ls should attach to the buffer
=> fix(scratchpad): Attach Lua LSP to buffer when entering scratchpad buf

lua/legendary/toolbox.lua
Resolves: #376
Use the instructions provided in the issue
=> fix(api): Fix incorrect adjustment of visual mode marks

lua/legendary/api/executor.lua, lua/legendary/util.lua
Resolves: #379
1. Create a keymap that replaces a builtin keymap, like `gg` (First Line)
2. Call Legendary and select the builtin keymap
**Remarks**
I've testet this with my configuration (mostly functions, some anonymous keymaps, no commands or auto...)
=> feat(keymaps): Execute builtin keymaps without remapping

README.md, lua/legendary/config.lua, lua/legendary/init.lua, lua/legendary/integrations/lazy-nvim.lua
Resolves: #377 
1. Setup `legendary.nvim` with `require('legendary').setup({ lazy_nvim = { auto_register = true } })`
2. Set up a keymap through a lazy.nvim plugin spec like
```lua
{
'folke/flash.nvim',
keys = {
{
's',
function()
require('flash').jump()
end,
mode = { 'n', 'x', 'o' },
desc = 'Jump forwards',
},
{
'S',
function()
require('flash').jump({ search = { forward = false } })
end,
mode = { 'n', 'x', 'o' },
desc = 'Jump backwards',
},
},
}
```
3. The keymaps defined in the plugin spec should be loaded into legendary.nvim
=> feat(integrations): Optionally autoload keymaps from lazy.nvim plugin specs

README.md, doc/API.md, lua/legendary/api/cmds.lua, lua/legendary/api/db/client.lua, lua/legendary/api/executor.lua, lua/legendary/data/autocmd.lua, lua/legendary/data/command.lua, lua/legendary/data/function.lua, lua/legendary/data/itemlist.lua, lua/legendary/data/keymap.lua, lua/legendary/data/state.lua, lua/legendary/init.lua, lua/legendary/ui/init.lua
Resolves: #384 
1. Run `legendary.nvim`'s finder UI and select a command
2. Call `:LegendaryRepeat` or `:lua require('legendary').repeat_previous()`
3. It should execute the last selected item again
=> feat(api): Add command + API to repeat last selected item

lua/legendary/api/executor.lua
Resolves: #375
1. select a range with `v`, `V` or `<c-v>`
2. escape
3. select a range with a different type and leave the cursor on either side
4. start legendary and choose a builtin motion (e.g. "Start of next word")
5. assert the type of visual mode and cursor side didn't change
=> fix(executor): Preserve type of visual mode

doc/API.md, doc/FILTERS.md, doc/table_structures/COMMANDS.md, doc/table_structures/FUNCTIONS.md, doc/table_structures/KEYMAPS.md, lua/legendary/data/itemlist.lua, lua/legendary/ui/init.lua
Resolves: #390 
1. Run `require('legendary').find({ itemgroup = 'Name of an item group' })`
2. It should start the finder with just the items inside that item group
=> feat(api): Add API to start finder from a specified root item group

doc/EXTENSIONS.md
Hi,
I just updated my config according to the recent change in the lazy.nvim extension to legendary.nvim. I figured that the configuration example of the lazy.nvim extension in the docs seems to have a typo, cf. the committed change to EXTENSIONS.md in this PR.
=> fix(docs): fix typo in lazy.nvim extension config

doc/WHICH_KEY.md, lua/legendary/extensions/which_key.lua, lua/legendary/util/which_key.lua
Resolves: #404 
1. Which-key.nvim integration should work
=> fix(extension): Fix extension configuration for which-key.nvim extension

lua/legendary/extensions/lazy_nvim.lua
Resolves: #408 
1. Lazy.nvim extension should load keymaps from plugin specs
=> fix(extension): Fix lazy.nvim extension from breaking change upstream

README.md, lua/legendary/api/executor.lua, lua/legendary/data/itemlist.lua, lua/legendary/data/state.lua, lua/legendary/ui/init.lua
https://github.com/mrjones2014/legendary.nvim/assets/8136158/17e19ca5-2bb6-4fe8-8dfb-e8aad186e893
* Remember most recent selection per global list and per itemlist
* Minor refactoring
* For global itemlist, most recently selected item is kept at `State.most_recent_item`
* For itemgroup-relative selection the `State.itemgroup_history[id]` map is used
* Exposed APIs aren't affected; only UX; 
=> feat(ui): keep track of recently used item

lua/legendary/extensions/which_key.lua
Resolves: #417 
1. Setting `extensions.which_key.auto_register = false` should be respected
=> fix(extension): Make which_key extension respect auto_register config

lua/legendary/ui/scratchpad.lua
Resolves: #420 
1. Type `return false` in scratchpad
2. Eval lua
3. Should show returned boolean instead of saying "no return value"
=> fix(scratchpad): Treat boolean false as a valid return value

lua/legendary/ui/init.lua
Resolves: #435 
1. Have an item group
2. Trigger the API via `require('legendary').find({ itemgroup = "my group" })`
3. It should start the finder with items from the group
=> fix(api): Apply `itemgroup` filter correctly

lua/legendary/toolbox.lua
Resolves: #437 
Follow reproduction steps described in issue.
=> fix(api): Fix toolbox functions to work if items are deepcopied

lua/legendary/ui/init.lua
Resolves: #440 
1. `:lua require('legendary').find({ select_prompt = 'Custom prompt' })`
=> fix(ui): Fix validation for `select_prompt` option

lua/legendary/data/keymap.lua, lua/legendary/init.lua
`vim.tbl_islist()` is deprecated and will be removed in Neovim 0.12. This causes depcrecation warnings on 0.11.
ref: https://github.com/neovim/neovim/blob/512d228111bccf3e52613c798edc7f803c1de13f/runtime/doc/deprecated.txt#L68
=> refactor: use `vim.islist()` instead of deprecated `vim.tbl_islist()`

.github/workflows/lint.yml, Makefile, lua/legendary/api/db/client.lua, lua/legendary/api/db/wrapper.lua, lua/legendary/data/itemlist.lua, tests/legendary/to_bytes_spec.lua, tests/testrc.lua
Resolves: #472 
1. Note that existing frecency data will unfortunately be invalid because the ID algorithm changed.
2. Try an item with a `'`' and/or `"` in the description e.g.
```lua
return {
'kylechui/nvim-surround',
version = "*", -- Use for stability; omit to use `main` branch for the latest features
keys = {
{ "<leader>'", '<Cmd>normal cs"\'<CR>', desc = 'Change surrounding " to \'' },
{ '<leader>"', '<Cmd>normal cs\'"<CR>', desc = 'Change surrounding \' to "' },
},
config = function ()
require('nvim-surround').setup({ })
end
}
```
with `lazy_nvim` extension and the frecency sorting enabled.
=> fix(frecency)!: Use byte strings for DB IDs
