.gitignore
README.md
lua/legendary/compat/which-key.lua
lua/legendary/config.lua
lua/legendary/executor.lua
lua/legendary/init.lua
lua/legendary/util.lua

Resolves #7 
Adds an automatic and manual way to load which-key tables into legendary.nvim.

implement which-key.nvim integration

---

README.md
lua/legendary/bindings.lua
lua/legendary/config.lua
lua/legendary/executor.lua
lua/legendary/init.lua
lua/legendary/util.lua
plugin/legendary.lua

Fixes #9 
Will allow end users to use these keys for sorting.
@cseickel will this allow you to do what you want?

set kind on vim.ui.select() and on keymap and command items

---

.github/workflows/gen-docs-txt.yml
README.md
lua/legendary/bindings.lua
lua/legendary/formatter.lua
lua/legendary/types.lua
plugin/legendary.lua

rewrite README.md

---

.github/workflows/lint.yml
.gitignore
Makefile
lua/legendary/bindings.lua
lua/legendary/config.lua
lua/legendary/executor.lua
lua/legendary/init.lua
lua/legendary/utils.lua
plugin/legendary.lua
tests/legendary/helpers_spec.lua
tests/legendary/utils_spec.lua
tests/testrc.lua

Fixes: #27 
Adds a basic test harness, cloning plenary.nvim into a `vendor/` directory, and using `:PlenaryBustedDirectory` command in a headless Neovim to run tests.

Set up a test harness and add some basic unit tests

---

README.md

Fixes: #28 
Changes we discussed over a week ago. First pass, more to become familiar with the collaboration process than actually change shit 😎 .
Review using `:MarkdownPreview` as that's what I used to verify changes. Note I used strikethrough in a couple places; ie, I did not actually delete words, but indicated some that 'might' want to go away.
Also be sure to advise on things like:
- how I worded commit message
- branch name? too long?
- the way I'm using this fork/submit pull request process
- anything workflow related you want to see me do different

#28 First pass, README edits

---

README.md
lua/legendary/bindings.lua
lua/legendary/executor.lua
lua/legendary/utils.lua

Fixes: #41 
I think I've got something that works pretty decent.
@tsyroid would you mind helping me test out this PR? Also looking at the added README.md changes.

Add support for executing visual mode commands and bindings

---

README.md
lua/legendary/bindings.lua
lua/legendary/builtins.lua

separate 'kind' for bultins

---

README.md
lua/legendary/bindings.lua
lua/legendary/formatter.lua

remove the hard requirement for a description from keymaps and commands

---

Makefile
lua/legendary/bindings.lua
lua/legendary/config.lua
lua/legendary/types.lua

add validators for table structures

---

README.md
lua/legendary/bindings.lua
lua/legendary/config.lua
lua/legendary/types.lua
plugin/legendary.lua

Option to show most recently used item at the top next time you open legendary

---

README.md
lua/legendary/bindings.lua
lua/legendary/utils.lua
tests/legendary/utils_spec.lua

Fixes #72 
Also makes it so that buffer-specific items are only shown for the current buffer.

Add support for buffer-local commands and show buffer-local items only for current buffer

---

lua/legendary/compat/which-key.lua

[which-key-register](https://github.com/folke/which-key.nvim#%EF%B8%8F-mappings)
`which_key_opts` may be nil when use register method 2 3 4.

Fix `which_key_opts` is nil

---

lua/legendary/bindings.lua
lua/legendary/executor.lua
lua/legendary/utils.lua

Fixes #76 
I believe this will fix your issue. I tested with some of the builtins like "Search word under cursor forward".
@olimorris can you test your keymapping on this branch?

restore cursor position before executing the item

---

README.md
lua/legendary/config.lua
lua/legendary/scratchpad.lua

add option to show :LegendaryScratch results in a floating window (new default option)

---

lua/legendary/bindings.lua
teal/legendary/bindings.tl

Accept `true` as key for `opts.buffer`

---

README.md

Fixes a small error in README.md.

fix error in README.md

---

lua/legendary/config.lua
teal/legendary/config.tl

Resolves: #174 
1. Any config changes you make should still apply
2. All features should work as intended and configured

refactor config.tl

---

.github/workflows/release.yml
CONTRIBUTING.md

generate GitHub Releases in CI

---

lua/legendary/data/itemgroup.lua
lua/legendary/data/itemlist.lua
lua/legendary/init.lua

internal(api): add iterator method to ItemList

---

.github/ISSUE_TEMPLATE/meta.yml
README.md

chore(docs): add Matrix chat link

---

.github/workflows/release.yml

update release CI to post release to Matrix channel

---

.github/workflows/check-pr-title.yml

validate PR titles

---

.github/workflows/gen-docs-txt.yml
.github/workflows/lint.yml

Resolves: #302 
Thanks @ibhagwan

chore: fix timestamps on vimdoc txt files

---

README.md
lua/legendary/config.lua

updates docs from changes in #308

chore: update docs

---

lua/legendary/integrations/which-key.lua

fix: Correctly fallback to another value when which-key group prefix is nil

---

lua/legendary/extensions/nvim_tree.lua

Uses nvim-tree API to load commands in extension

fix(extension): Use nvim-tree API to load commands in extension

---

README.md

chore(docs): Correct documentation about default opts

---

lua/legendary/api/db/wrapper.lua

For example, if sqlite is installed via nix, it won't find it.

fix(frecency): Make SQLite integration work for more setups

---

lua/legendary/api/db/wrapper.lua

Reverts this incorrect fix while I fix it upstream in https://github.com/kkharji/sqlite.lua/pull/169

fix(frecency): revert incorrect SQLite path lookup

---

README.md

chore(docs): Update README.md to include troubleshooting steps for frecency sort

---

README.md
lua/legendary/api/db/init.lua
lua/legendary/api/db/wrapper.lua
lua/legendary/data/itemlist.lua
lua/legendary/ui/init.lua

fix(frecency): Fail gracefully if sqlite not available or cannot open DB

---

lua/legendary/ui/init.lua

fix(api): Fix error when calling find() with nil options table

---

.envrc
.gitignore
CONTRIBUTING.md
Makefile
flake.lock
flake.nix

Resolves: #371 
1. `direnv allow`
2. `flake.nix` should be used
3. `stylua` and `luacheck` should be installed in your shell

chore: Add flake.nix for local development
